name: Release
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: 'Semantic Release'
        if: 'success()'
        env:
          GITHUB_TOKEN: '${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_AUTH_TOKEN }}'
          GIT_AUTHOR_NAME: 'github-actions-shell'
          GIT_AUTHOR_EMAIL: 'github-actions[bot]@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'github-actions-shell'
          GIT_COMMITTER_EMAIL: 'github-actions[bot]@users.noreply.github.com'
        run: 'pnpx multi-semantic-release'
